project:
  type: book
  output-dir: ../2-rendered

book:
  title: "minibook"
  author: "Hadley Wickham"
  chapters:
    - index.qmd
    - formatting.qmd
    - code.qmd
    - part: part-1.qmd
      chapters:
        - chap-1-1.qmd
        - chap-1-2.qmd
  appendices:
    - appendix-1.qmd
    - appendix-2.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

editor: visual

